name: Go build

on:
  push:
    tags:
    - v.*-stag
    - v.*-prod
    - v.*-test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG: mydemo

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: variables
      run: |
        TAG=${GITHUB_REF#refs/tags/v.}
        echo $TAG
        echo "REPO=${GITHUB_REPOSITORY,,}" >>$GITHUB_ENV
        echo "DTAG=${TAG%-*}" >>$GITHUB_ENV
        echo "DENV=${TAG#*-}" >>$GITHUB_ENV
        case "${TAG#*-}" in
        test*) echo "P2H=testv2.yocontribuyo.cl" >>$GITHUB_ENV
        	;;
        stag*) echo "P2H=staging.yocontribuyo.cl" >>$GITHUB_ENV
        	;;
        prod*) echo "P2H=yocontribuyo.cl" >>$GITHUB_ENV
        	;;
        esac
    - name: debug
      run: |
        echo ${{ env.REPO }}
        echo ${{ env.DTAG }}
        echo ${{ env.DENV }}
        echo ${{ env.P2H }}
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.GHA_CI_USERNAME }}
        password: ${{ secrets.GHA_CI_TOKEN   }}
        registry: docker.pkg.github.com
        repository: ${{ env.REPO }}/${{ env.PKG }}
        path: ${{ env.PKG }}-${{ env.DENV }}
        tags: ${{ env.DTAG }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
# vim: tabstop=2 shiftwidth=2 expandtab

