name: Go build

on:
  push:
    tags:
    - v.*-stag
    - v.*-prod
    - v.*-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: variables
      run: |
        TAG=${GITHUB_REF#refs/tags/v.}
        echo $TAG
        echo "REPO=${GITHUB_REPOSITORY,,}" >>$GITHUB_ENV
        echo "DTAG=${TAG%-*}" >>$GITHUB_ENV
        echo "DENV=${TAG#*-}" >>$GITHUB_ENV
	case "${TAG#*-}" in
	test*) echo "P2H=testv2.yocontribuyo.cl" >>$GITHUB_ENV
		;;
	stag*) echo "P2H=staging.yocontribuyo.cl" >>$GITHUB_ENV
		;;
	prod*) echo "P2H=yocontribuyo.cl" >>$GITHUB_ENV
		;;
	esac
    - name: debug
      run: |
        echo ${{ env.REPO }}
        echo ${{ env.DTAG }}
        echo ${{ env.DENV }}
