name: Build and Publish my test
on:
  push:
    branches:
    - master
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: marcefr/testactions/ejemplo-prod
        target: prod
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
on:
  push:
    branches:
    - test
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@test
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: marcefr/testactions/ejemplo-test
        target: prod
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
