name: Build and Publish my test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: docker.pkg.github.com/marcefr/testactions
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
