name: Build and Publish my test
on:
  push:
    #tag: '[0-9]+\.[0-9]+.*'
    branches: master
env:
  REF: ${{ github.ref }}
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - name: REF as var
      run: echo "REF=$REF"
    - name: checkout
      uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}    - name: docker images
    - name: build + push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: marcefr/testactions/ejemplo-prod
        #target: prod    - no se que onda
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        #push: true
    - name: docker images
      run: docker images
