name: Construye y publica backend
on:
  push:
    branches:
    - test
    tags:
    - "*/*.*.*"
env:
  oldcontainer: ehsmart-ehsmart
jobs:
  should_run:
    runs-on: ubuntu-latest
    steps:
    - name: check tagged
      if: startsWith(github.ref, 'refs/tags/') == failure()
      uses: andymckay/cancel-action@0.2
  # nombre del contenedor en el registry:
  ehsmart-backend:
    runs-on: ubuntu-latest
    steps:
    - name: variables I
      run: |
        t=${GITHUB_REF#refs/tags/}
        echo "::set-env name=MSTAG::${GITHUB_REF##*/}"
        echo "::set-env name=MSDIR::${t%/*}"
    - name: variables I
      run: |
        echo ${{ env.MSTAG }}
        echo ${{ env.MSDIR }}
        echo =========
        env|sort
    - name: source checkout
      uses: actions/checkout@v2.3.2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/${{ github.job }}
        path: 
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: docker-compose gen
      run: DCVER=${GITHUB_REF#refs/tags/} envsubst <docker-compose-test.yaml >docker-compose.yaml
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      continue-on-error: true
      with:
        host: ehsmart-test.e-captum.com
        username: ubuntu
        use_insecure_cipher: true
        cipher: # optional
        key: ${{ secrets.GHA_CI_SSHKEY }}
        key_path: # optional
        envs: oldcontainer
        script: |
          test -d ~/Actions/${{ github.job }} || docker rm -f $oldcontainer
        script_stop: true
        debug: # optional
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ubuntu@ehsmart-test.e-captum.com
        ssh_public_key: ${{ secrets.GHA_CI_SSHPUB }}
        ssh_private_key: ${{ secrets.GHA_CI_SSHKEY }}
        args: "up -d"
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: ~/Actions/${{ github.job }}
        pull_images_first: true
