name: Build and Publish my test
on:
  push:
    branches:
    - test
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - name: variables
      run: echo $GITHUB_REPOSITORY
    - uses: actions/checkout@v2.3.2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: marcefr/testactions/ejemplo-test
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
