name: Build and Publish my test
on:
  push:
    branches:
    - test
    tags:
    - "*.*"
jobs:
  # nombre del contenedor en el registry
  marcelo:
    runs-on: ubuntu-latest
    steps:
    - name: variables
      run: |
        env|sort
    - uses: actions/checkout@v2.3.2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/${{ github.job }}
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: docker-compose gen
      run: DCVER=${GITHUB_REF#refs/tags/} envsubst <docker-compose-test.yaml >docker-compose.yaml
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ehsmart-test.e-captum.com
        # ssh key passphrase
        passphrase: # optional
        username: ubuntu
        # include more ciphers with use_insecure_cipher
        use_insecure_cipher: # optional
        # the allowed cipher algorithms. If unspecified then a sensible
        cipher: # optional
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.GHA_CI_SSHKEY }}
        # path of ssh private key
        key_path: # optional
        # sha256 fingerprint of the host public key
        fingerprint: ${{ secrets.GHA_CI_SSHPUB }}
        # execute commands
        script: docker rm -f marcelo_running
        # stop script after first failure
        script_stop: true
        # pass environment variable to shell script
        envs: # optional
        # enable debug mode
        debug: # optional    - name: Docker Deployment
          uses: wshihadeh/docker-deployment-action@v1
          with:
            remote_docker_host: ubuntu@ehsmart-test.e-captum.com
            ssh_public_key: ${{ secrets.GHA_CI_SSHPUB }}
            ssh_private_key: ${{ secrets.GHA_CI_SSHKEY }}
            args: "up -d"
            deployment_mode: docker-compose
            copy_stack_file: true
            deploy_path: ~/Actions/${{ github.job }}
            pull_images_first: true
