name: Construye y publica backend
on:
  push:
    branches:
    - test
    tags:
    - "*/*.*.*"
env:
  oldcontainer: ehsmart-ehsmart
jobs:
  should_run:
    runs-on: ubuntu-latest
    steps:
    - name: check tagged
      if: startsWith(github.ref, 'refs/tags/') == failure()
      uses: andymckay/cancel-action@0.2
  # nombre del contenedor en el registry:
  ehsmart-backend:
    runs-on: ubuntu-latest
    steps:
    - name: source checkout
      uses: actions/checkout@v2.3.2
    - name: variables
      run: |
        t=${GITHUB_REF#refs/tags/}
        echo "::set-env name=MSTAG::${GITHUB_REF##*/}"
        echo "::set-env name=MSDIR::${t%/*}"
        case $t in
        nginx*) p=5000
                ;;
        *) p=""
                ;;
        esac
        echo "::set-env name=MSPORT::${p}"
    - name: docker-compose gen
      run: |
        envsubst <docker-compose-test.yaml >docker-compose.yaml
        test -z "${{ env.MSPORT }}" || sed -i 's/^#MSPORT.*/    port:\n        - ${{ env.MSPORT }}:${{ env.MSPORT }}/' docker-compose-test.yaml
    - name: como te quedo el compose?
      run: cat docker-compose.yaml
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/${{ env.MSDIR }}-test
        path: ${{ env.MSDIR }}
        tags: ${{ env.MSTAG }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      continue-on-error: true
      with:
        host: ehsmart-test.e-captum.com
        username: ubuntu
        use_insecure_cipher: true
        cipher: # optional
        key: ${{ secrets.GHA_CI_SSHKEY }}
        key_path: # optional
        envs: oldcontainer
        script: |
          test -d ~/Actions/${{ env.MSDIR }} || docker rm -f $MSDIR-ehsmart
        script_stop: true
        debug: # optional
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ubuntu@ehsmart-test.e-captum.com
        ssh_public_key: ${{ secrets.GHA_CI_SSHPUB }}
        ssh_private_key: ${{ secrets.GHA_CI_SSHKEY }}
        args: "up -d --remove-orphans"
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: ~/Actions/${{ env.MSDIR }}
        pull_images_first: true
